"""Builds the per-entity due-diligence report.

One structure feeds both the on-screen report and the PDF, so the document a
lawyer files can never say something different from the screen it was read on.
"""
from datetime import date, datetime
from typing import List, Optional

from graph import band_reason, risk_band
from sources import demo as demo_source
from sources import opensanctions
from reference import country_label, jurisdiction_label
from schema import COMPANY, DIRECTS, OWNS, PERSON, POSSIBLY_SAME_AS, SHAREHOLDER_OF

CONTROL_TYPES = {OWNS, SHAREHOLDER_OF, DIRECTS}
ROLE_LABEL = {
    OWNS: "Owner",
    SHAREHOLDER_OF: "Shareholder",
    DIRECTS: "Director / officer",
    "registered_at": "Registered address",
    "linked_to": "Associated with",
}

DISCLAIMER = (
    "Generated by UBOgraph from the sources listed against each record. Findings "
    "are leads for a human reviewer, not conclusions: a shared registered address, "
    "a high directorship count or an offshore registration each have entirely "
    "legitimate explanations and must be verified against primary records before "
    "any decision is taken. Entities marked as a possible identity match have NOT "
    "been merged and may be different people."
)

END_DATE_NOTE = (
    "Affiliations are classified as previous only where an end date is recorded. "
    "Registries do not consistently publish end dates, so an entry shown as current "
    "may in fact have ended."
)


def _is_past(value: Optional[str]) -> bool:
    """No end date recorded means the affiliation is treated as current."""
    if not value:
        return False
    text = str(value).strip()
    for fmt, length in (("%Y-%m-%d", 10), ("%Y-%m", 7), ("%Y", 4)):
        try:
            return datetime.strptime(text[:length], fmt).date() <= date.today()
        except ValueError:
            continue
    return True  # an end date we cannot parse is still an end date


def _node_index(payload: dict) -> dict:
    return {n["id"]: n for n in payload.get("nodes", [])}


def _describe_share(edge: dict) -> str:
    share = edge.get("share_pct")
    return f"{share:g}%" if isinstance(share, (int, float)) else ""


def build_report(payload: dict, node_id: str) -> dict:
    nodes = _node_index(payload)
    subject = nodes.get(node_id)
    if not subject:
        return {"error": "That entity is not in the current result set."}

    edges = payload.get("edges", [])
    flags = list(subject.get("risk_flags") or [])
    score = int(subject.get("risk_score") or 0)
    band = subject.get("risk_band") or risk_band(score, flags)

    # --- affiliations -------------------------------------------------
    current, previous = [], []
    for edge in edges:
        if edge.get("type") not in CONTROL_TYPES:
            continue
        if edge.get("source") != node_id:
            continue
        other = nodes.get(edge.get("target"))
        if not other:
            continue
        entry = {
            "id": other["id"],
            "name": other.get("name"),
            "type": other.get("type"),
            "role": ROLE_LABEL.get(edge["type"], edge["type"]),
            "detail_role": edge.get("role") or "",
            "share": _describe_share(edge),
            "start_date": edge.get("start_date"),
            "end_date": edge.get("end_date"),
            "jurisdiction": jurisdiction_label(other.get("jurisdiction") or other.get("country")),
            "reg_number": other.get("reg_number"),
            "status": other.get("status"),
            "band": other.get("risk_band") or risk_band(
                int(other.get("risk_score") or 0), other.get("risk_flags")
            ),
            "flags": list(other.get("risk_flags") or []),
            "source": edge.get("origin"),
        }
        (previous if _is_past(edge.get("end_date")) else current).append(entry)

    order = {"red": 0, "orange": 1, "green": 2}
    current.sort(key=lambda a: (order.get(a["band"], 3), a["name"] or ""))
    previous.sort(key=lambda a: (order.get(a["band"], 3), a["name"] or ""))

    # --- who controls the subject (for company subjects) --------------
    controllers = []
    for edge in edges:
        if edge.get("target") == node_id and edge.get("type") in CONTROL_TYPES:
            other = nodes.get(edge.get("source"))
            if other:
                controllers.append({
                    "id": other["id"],
                    "name": other.get("name"),
                    "role": ROLE_LABEL.get(edge["type"], edge["type"]),
                    "share": _describe_share(edge),
                    "band": other.get("risk_band") or "green",
                })

    # --- findings that name this entity -------------------------------
    findings = [
        {
            "severity": f["severity"],
            "title": f["title"],
            "detail": f["detail"],
            "kind": f.get("kind"),
        }
        for f in payload.get("findings", [])
        if node_id in (f.get("nodes") or [])
    ]

    # --- ownership route to the searched company ----------------------
    ownership_paths = [
        {"tiers": u.get("tiers"), "path": u.get("path") or []}
        for u in payload.get("ubos", [])
        if u.get("id") == node_id
    ]

    # --- unresolved identity matches ----------------------------------
    identity_matches = []
    for edge in edges:
        if edge.get("type") != POSSIBLY_SAME_AS:
            continue
        if node_id not in (edge.get("source"), edge.get("target")):
            continue
        other_id = edge["target"] if edge["source"] == node_id else edge["source"]
        other = nodes.get(other_id)
        if other:
            identity_matches.append({
                "id": other_id,
                "name": other.get("name"),
                "confidence": edge.get("confidence"),
                "note": edge.get("role") or "",
            })

    dossier, dossier_error = _load_dossier(subject)

    return {
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "dossier": dossier,
        "dossier_error": dossier_error,
        "query": payload.get("query", {}),
        "demo_mode": payload.get("demo_mode", False),
        "subject": {
            "id": subject["id"],
            "name": subject.get("name"),
            "type": subject.get("type"),
            "aliases": subject.get("aliases") or [],
            "country": subject.get("country"),
            "country_label": country_label(subject.get("country")),
            "jurisdiction_label": jurisdiction_label(subject.get("jurisdiction")),
            "birth_date": subject.get("birth_date"),
            "reg_number": subject.get("reg_number"),
            "status": subject.get("status"),
            "sources": subject.get("sources") or [],
            "source_urls": subject.get("source_urls") or [],
            "notes": subject.get("notes") or [],
            "risk_score": score,
            "risk_band": band,
            "band_reason": subject.get("band_reason") or band_reason(score, flags),
            "flags": flags,
        },
        "narrative": _narrative(subject, findings, current, previous, ownership_paths, band),
        "findings": findings,
        "affiliations": {"current": current, "previous": previous},
        "controllers": controllers,
        "ownership_paths": ownership_paths,
        "identity_matches": identity_matches,
        "media": payload.get("adverse_media"),
        "disclaimer": DISCLAIMER,
        "end_date_note": END_DATE_NOTE,
    }


def _load_dossier(subject: dict):
    """Full source detail for the subject, fetched on demand.

    Only runs when a report is opened, so a search of twenty entities does not
    pull twenty dossiers nobody asked for.
    """
    raw_ids = [
        source_id.split(":", 1)[1]
        for source_id in (subject.get("source_ids") or [])
        if source_id.startswith("opensanctions:")
    ]
    if raw_ids and opensanctions.available():
        try:
            return opensanctions.fetch_dossier(raw_ids), None
        except Exception as exc:
            return None, str(exc)[:240]
    if str(subject.get("id", "")).startswith("demo:"):
        return demo_source.dossier_for(subject["id"]), None
    if raw_ids:
        return None, "OpenSanctions key not configured — detail not fetched."
    return None, None


def _narrative(subject, findings, current, previous, paths, band) -> List[str]:
    """Plain-English paragraphs explaining the band. Deterministic, not generated."""
    name = subject.get("name") or "This entity"
    is_person = subject.get("type") == PERSON
    flags = set(subject.get("risk_flags") or [])
    paragraphs = []

    opening = {
        "red": f"{name} is banded RED.",
        "orange": f"{name} is banded ORANGE.",
        "green": f"{name} is banded GREEN.",
    }[band]
    paragraphs.append(opening + " " + (subject.get("band_reason") or ""))

    if "sanctioned" in flags:
        paragraphs.append(
            f"{name} appears on a sanctions list in the sources searched. Any dealing "
            "with a listed party may itself be prohibited — confirm the listing against "
            "the issuing authority's own register before proceeding."
        )
    if "sanction_linked" in flags:
        paragraphs.append(
            f"{name} is recorded as linked to a sanctioned party and is NOT itself "
            "sanctioned. Establish the nature of the connection: depending on ownership "
            "and control, a link can bring an entity within the measures, or be immaterial."
        )
    if "pep" in flags:
        paragraphs.append(
            f"{name} holds or has held public office and is recorded as a politically "
            "exposed person. That is a status, not an allegation — it is not a sanctions "
            "listing and implies no wrongdoing. It raises the standard of source-of-funds "
            "enquiry and calls for senior sign-off under most AML policies."
        )
    if "pep_associate" in flags:
        paragraphs.append(
            f"{name} is recorded as a relative or close associate of a politically "
            "exposed person. As with PEP status itself, this is a prompt for enhanced "
            "due diligence rather than an adverse finding."
        )
    if "debarred" in flags:
        paragraphs.append(
            f"{name} appears on a debarment or export-control listing. Check the issuing "
            "body's own register for the scope and current status of the measure."
        )
    if "leak" in flags:
        paragraphs.append(
            f"{name} appears in leaked offshore records. Appearing in a leak is not "
            "evidence of an offence, but it does mean the entity's offshore activity "
            "is documented outside official registries."
        )

    controlled = len(current)
    if is_person and controlled:
        jurisdictions = sorted({a["jurisdiction"] for a in current if a["jurisdiction"]})
        sentence = (
            f"{name} holds {controlled} current controlling role"
            f"{'' if controlled == 1 else 's'} in this network"
        )
        if jurisdictions:
            sentence += ", across " + ", ".join(jurisdictions[:6])
            if len(jurisdictions) > 6:
                sentence += f" and {len(jurisdictions) - 6} more"
        paragraphs.append(sentence + ".")
        red_entities = [a["name"] for a in current if a["band"] == "red"]
        if red_entities:
            paragraphs.append(
                "Of those, the following are themselves banded red: "
                + ", ".join(red_entities[:8]) + "."
            )
    if previous:
        paragraphs.append(
            f"{len(previous)} affiliation{'' if len(previous) == 1 else 's'} "
            f"{'is' if len(previous) == 1 else 'are'} recorded as ended. "
            "Historic roles still matter: they establish what the subject knew and when."
        )

    for path in paths:
        if path.get("path"):
            paragraphs.append(
                f"Ownership runs from {name} to {path['path'][-1]} through "
                f"{path.get('tiers')} tier(s): " + " → ".join(path["path"]) + "."
            )

    structural = [f for f in findings if f.get("kind") in
                  {"circular_ownership", "nominee_hub", "shared_address", "deep_layering"}]
    if structural:
        paragraphs.append(
            "Structural findings involving this entity: "
            + "; ".join(f["title"] for f in structural)
            + ". Each is a pattern worth explaining, not proof of anything on its own."
        )

    if band == "green" and not findings:
        paragraphs.append(
            "Nothing adverse was found in the sources searched. That is an absence of "
            "evidence, not a clearance — coverage varies by jurisdiction, and free-zone "
            "registries in particular publish little ownership data."
        )
    return paragraphs
